-- Create the table if it doesn't exist with id as BIGINT and auto-incrementing
CREATE TABLE IF NOT EXISTS application_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO application_user (id, name) VALUES (6, 'John Doe');
INSERT INTO application_user (id, name) VALUES (7, 'Jane Smith');
INSERT INTO application_user (id, name) VALUES (8, 'Michael Brown');
INSERT INTO application_user (id, name) VALUES (9, 'Emily Davis');